---
title: "Plano de ensino"
author: "Maurício Vancine"
date: "25/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introdução ao uso de dados geoespaciais no R

### Docentes responsáveis

Prof. Dr. Milton Cezar Ribeiro 

Prof. Me. Maurício Humberto Vancine

### Carga horária

60 h (4 créditos)

### Participantes

10 alunos (+ 5 especiais)

### Datas e horários

Teórico-prático: 25/10/2021 a 29/10/2021 (9-17h)

Exercícios-atividades assistidas remotamente: 01/11/2021 a 05/11/2021 (9-17h)

### Repositório de dados da disciplina

https://github.com/mauriciovancine/course-geospatial-data-r

### Resumo

A disciplina oferecerá os principais conceitos teóricos e práticos quanto ao funcionamento da linguagem R e seu uso para manipulação e visualização de dados tabulares e geoespaciais, com enfoque em Ecologia Geral. Serão abordados os seguintes temas: (1) controle de versão, git e GitHub, (2) funcionamento da linguagem R, (3) estrutura e manipulação de dados no R, (4) introdução ao tidyverse, (5) visualização de dados no R, (6) estrutura e fonte de dados geoespaciais, (7) estrutura e manipulação de dados vetoriais no R, (8) estrutura e manipulação de dados matriciais no R e (9) visualização de dados geoespaciais no R. A carga horária total será de 60 horas, onde nos cinco dias iniciais serão ministrados 6 horas de aulas teórico-práticas, num total de 30 horas. As 30 horas restantes serão direcionadas à formulação e execução de um projeto com dados reais, como forma de avaliação para compor a nota final da disciplina. Após a realização da disciplina, espera-se que as alunas e alunos adquiram conceitos gerais sobre a estrutura, manipulação e visualização de dados tabulares e geoespaciais, assim como domínio das técnicas e métodos para alcançar autonomia e produzir soluções para suas próprias questões relativas à geocomputação utilizando a linguagem R.

### Conteúdo

### 1 Controle de versão, git e GitHub

1. Conferir os computadores
1. Controle de versão
1. git e GitHub
1. Funcionamento do controle de versão
1. GitHub: Fork
1. Configuração: RStudio, git, GitHub
1. Iniciando localmente: git init
1. Iniciando remotamente: git clone
1. Versionamento: git add, git commit e git status
1. Ignorando: .gitignore
1. Histórico: git log e git show
1. Diferenças: git diff
1. Desfazer: git revert e git reset 
1. Ramificações: git branch, git switch e git merge
1. Remoto: git remote, git push e git pull
1. GitHub: Pull request
1. Detalhes do repositório do GitHub
1. Interface gráfica do RStudio
1. Principal material de estudo

### 2 Funcionamento da linguagem R

1. Linguagem R
1. RStudio
1. Console
1. Scripts
1. Operadores
1. Objetos
1. Funções
1. Pacotes
1. Ajuda
1. Ambiente
1. Citações
1. Principais erros
1. Principal material de estudo

### 3 Estrutura e manipulação de dados

1. Atributos dos objetos
1. Manipulação de dados unidimensionais
1. Manipulação de dados multidimensionais
1. Valores faltantes e especiais
1. Diretório de trabalho
1. Importar dados
1. Conferência de dados importados
1. Exportar dados

### 4 Introdução ao tidyverse

1. Contextualização
1. tidyverse
1. here
1. readr, readxl e writexl
1. tibble
1. magrittr (pipe - %>%)
1. tidyr
1. dplyr
1. stringr
1. forcats
1. lubridate
1. purrr

### 5 Visualização de dados

1. Contextualização
1. Pacotes para produção de gráficos
1. Gramática dos gráficos
1. Principal material de estudo 
1. Principais tipos de gráficos 
1. Histograma e Densidade
1. Gráfico de setores
1. Gráfico de barras
1. Gráfico de caixas
1. Gráfico de dispersão
1. Gráfico pareado
1. Combinando gráficos
1. Gráficos animados
1. Gráficos interativos
1. Gráficos usando interface

### 6 Estrutura e fonte de dados geoespaciais

1. Geoprocessamento
1. Cartografia
1. *Global Positioning System* (GPS)
1. Sensoriamento Remoto
1. Sistema de Informação Geográfica (SIG)
1. Dados geoespaciais
1. Dados vetoriais
1. Dados matriciais (gride ou raster)
1. Conversão de dados geoespaciais (vetor-raster)
1. Banco de dados geoespaciais
1. Principais fontes de dados geoespaciais
1. Principal material de estudo

### 7 Estrutura e manipulação de dados vetoriais

1. Principais pacotes
1. Geometrias sf
1. Classes sf
1. Importar dados vetoriais
1. Descrição de objetos sf
1. Converter objetos para sf
1. Converter CRS de objetos sf
1. Operações de objetos sf
1. Exportar objetos sf

### 8 Estrutura e manipulação de dados matriciais

1. Principais pacotes
1. Classes raster
1. Importar dados matriciais
1. Descrição de objetos raster
1. Converter CRS de objetos raster
1. Operações de objetos raster
1. Interações raster-vetor
1. Conversões raster-vetor
1. Índices espectrais
1. Exportar objetos raster

### 9 Visualização de dados geoespaciais

1. Elementos de um mapa
1. Pacotes para produção de mapas
1. Mapas estáticos
1. Mapas animados
1. Mapas interativos

### Referências

Adler J. 2012. R in a Nutshell: A Desktop Quick Reference. 2 ed. O'Reilly Media.

atlan. 2019. Introduction to GIS: Manipulating and Mapping Geospatial Data in R. [https://cdn2.hubspot.net/hubfs/2287011/Atlan%20GIS%20Course/All%20lessons.pdf]

Bivand RS, Pebesma E, Gómez-Rubio V. 2013. Applied Spatial Data Analysis with R. 2 ed. Springer.

Brunsdon C, Comber L. 2015. An introduction to R for spatial analysis & mapping. SAGE Publications.

Chang W. 2013. R Graphics Cookbook: Practical Recipes for Visualizing Data. 2 ed. O'Reilly Media. [https://r-graphics.org/]

Chacon S., Straub B. 2014. Pro Git. 2 ed. Apress. [https://git-scm.com/book/en/v2]

Cotton R. 2013. Learning R: A Step-by-Step Function Guide to Data Analysis. O'Reilly Media.

Davies TM. 2016. The Book of R: A First Course in Programming and Statistics. No Starch Press.

Engel C. 2019. R for Geospatial Analysis and Mapping. The Geographic Information Science & Technology Body of Knowledge (1st Quarter 2019 Edition), John P. Wilson (Ed.). DOI: 10.22224/gistbok/2019.1.3.

Engel C. 2019. Introduction to R. [https://cengel.github.io/R-intro/]

Engel C. 2019. Using Spatial Data with R. [https://cengel.github.io/R-spatial/]

Fitz PR. 2008. Geoprocessamento sem complicação. Oficina de Textos. 

Fletcher R, MJ Fortin. 2019. Spatial Ecology and Conservation Modeling: applications with R. Springer.

Hastle T, Tibshirani R, Friedman J. 2016. The Elements of Statistical Learning: Data Mining, Inference, and Prediction. 2 ed. Springer. [https://web.stanford.edu/~hastie/ElemStatLearn/ ] . 

Healy K. 2019. Data Visualization: a practical introduction. Princeton University Press.

Hijmans, R. 2019. Spatial Data Analysis and Modeling with R. [http://rspatial.org]

Horning N, Robinson JA, Sterling EJ, Turner W, Spector S. 2010. Remote Sensing for Ecology and Conservation: A Handbook of Techniques. Oxford University Press.

James G, Witten D, Hastie T, Tibshirani R. 2013. An Introduction to Statistical Learning: with Applications in R. 2.ed. Springer. [http://faculty.marshall.usc.edu/gareth-james/ISL/]

Kabacoff RI. 2015. R in Action: Data analysis and graphics with R. 2.ed. Manning.

Lander JP. 2017. R for Everyone: Advanced Analytics and Graphics. Addison-Wesley Professional.

Lepaine M, Usery EL. 2017. Choosing a Map Projection. Springer.

Lovelace R, Nowosad J, Muenchow, J. 2019. Geocomputation with R. Chapman and Hall/CRC. [https://geocompr.robinlovelace.net/]

Mas J, Horta MB, Vasconcelos RN, Cambui ECB. 2019. Análise espacial com R. UEFS Editora. [https://bit.ly/2KpSI7C]

Matloff N. 2011. The Art of R Programming: A Tour of Statistical Software Design. No Starch Press.

Oliveira PF, Guerra S, Mcdonnell, R. 2018. Ciência de dados com R – Introdução. IBPAD. [https://cdr.ibpad.com.br/]

Pebesma, E. 2018. Simple Features for R: Standardized Support for Spatial Vector Data. The R Journal, 10(1):439–446.

Pebesma E, Bivand R. 2019. Spatial Data Science. [https://keen-swartz-3146c4.netlify.com/]

R Core Team. 2020. R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. [https://www.r-project.org/]

Teetor P. 2011. R Cookbook. O'Reilly Media. [http://www.cookbook-r.com/]

Xavier-da-Silva J. 2009. O que é Geoprocessamento? Revista do CREA-RJ , 79:42–44.

Wegmann M, Leutner B, Dech S. 2016. Remote Sensing and GIS for Ecologists. Pelagic Publishing. 

Wickham H, Grolemund, G. 2017. R for Data Science: Import, Tidy, Transform, Visualize, and Model Data. O'Reilly Media. [https://r4ds.had.co.nz/]

Wickham H. 2019. Advanced R. 2 ed. Chapman and Hall/CRC. [https://adv-r.hadley.nz/]

Wickham H. 2020. ggplot2: Elegant Graphics for Data Analysis. 3 ed. Springer. [https://ggplot2-book.org/]

Wilk CO. 2019. Fundamentals of Data Visualization: A Primer on Making Informative and Compelling Figures. O'Reilly Media. [https://serialmentor.com/dataviz/]